### ISSUE TITLE
[BUG] Server crashes when dropping Anvil onto Citrine Cluster (dropped items)

### ISSUE THREAD

**Issue by ZenithAstralis** [itsdinkd/AQM2#34] opened 2022-01-03 10:52 UTC
**Modpack Version**
AQM2 1.5.1

**Minecraft Version**
1.18.1

**Describe the bug**
The Spectrum mod led me to believe I should smash gems with anvils. It worked fine for Amethyst, but when using Citrine (specifically the clusters which grow renewably inside geodes) it crashes the server.

**To Reproduce**
1. Go to a Spectrum mod spawned Citrine geode and grab some of the clusters (confirmed with at least the full sized ones)
2. Throw 'em on the Ground (with Q)
3. Right click to place an Anvil (vanilla - mine was "chipped") above them so that it falls onto the block where they're floating

**Expected behavior**
Should drop the Spectrum mod's citrine dust piles, like it does for Amethyst

**Screenshots**
[Hope these help somwhat!](https://imgur.com/a/3MPnBsn)

**Crash log or latest.log.log**
[*Crash-log*](https://paste.corebot.dev/fematusuqi.php)

**Additional context**
Maybe this helps somehow?
https://github.com/DaFuqs/Spectrum/wiki/Custom-Anvil-Crushing-Recipes

**Comment by Antoninecek** [comment] 2022-01-03 13:43
duplicate of  #25

**Closed** 2022-01-09 19:28 UTC
Labels: bug
