### ISSUE TITLE
[BUG] Storage Cabinets disappear next to Modern Industrialization Item Pipes

### ISSUE THREAD

**Issue by dundonsx2** [itsdinkd/AQM2#113] opened 2022-02-03 17:54 UTC
Modpack Version
AQM2 2.0.2

Minecraft Version
1.18.1

**Describe the crash or bug**
When you place a Storage Cabinet next to a Modern Industrialization item pipe, the cabinet will disappear upon interaction

**Steps to reproduce the behavior:**
1. Place Storage Cabinet next to a MI item pipe 
2. Attempt to interact with the Storage Cabinet (right clicking on it)

**Expected behavior**
The cabinet will disappear, although you can force it to reappear by interacting with a block behind it within range.

**Screenshots**
![image](https://user-images.githubusercontent.com/61992511/152400313-416de4de-e54f-42fb-81a5-410b64671490.png)
![image](https://user-images.githubusercontent.com/61992511/152400364-37b4864a-319c-4291-b835-4e2be733ede4.png)
![image](https://user-images.githubusercontent.com/61992511/152400388-24f7e4df-0605-49e8-a6aa-e0f726f60cc1.png)

**Additional context**
I have placed Storage Cabinets near other areas and on their own and they do not appear to have this problem. I also have some set up to Tom's Simple Storage and they still do not have this problem. Just next to MI Item Pipes.

Additionally, they do seem to function as if they are there even if they disappear. I ran my setup with a few of them disappeared and the item pipes registered them as existing.

**Comment by itsdinkd** [comment] 2022-02-04 04:44
Issue with fabric api at the moment / video rendering. 

Try these steps to temp solve
1) Refresh chunks in game by pressing F3 + A
2) if that fails, try removing Iris
3) If that fails, try removing Indium

**Comment by kiartu** [comment] 2022-02-04 16:54
Just adding: The users on the server I manage have given up until it's fixed. I've replicated the issue locally with Tech Reborn cables, and nearly every AE2 placeable item (cables/processors/cable covers/even controllers). Can't access AE2 storage when display's aren't accessible =)

I've attempted all 3 of your temp solve solutions itsdinkd. Unfortunately none have worked. Removing Iris didn't appear to do anything locally, removing Indium made it *much* much* worse (there are 3 screens, a couple dozen cables, and some drive bays from AE2 in this screenshot, well... supposed to be ;P)

![Screenshot 2022-02-04 085301](https://user-images.githubusercontent.com/29462610/152569559-38ae3b77-69a3-4c78-be2c-78fe90fbf06c.png)

**Comment by DragonLight** [comment] 2022-02-04 18:56
Unfortunately none of those temp fixes worked for us. Only temp fix we found that worked was logging out and back into server to get blocks to show again, but after some time they would still disappear.

**Comment by vydax** [comment] 2022-02-05 19:50
this happens not only for those blocks but various other blocks, had waystones dissapear, had blocks from valleycraft dissapear , from all the various tech mods dissapear tech reborn/modern ind/toms simple storage/ ae2 this is a wide variety that tends to dissapear.

**Comment by dundonsx2** [comment] 2022-02-05 23:23
Server I am on updated to 2.0.2a and can confirm this is still happening.

**Comment by recon88** [comment] 2022-02-07 07:44
Can confirm, the workarounds do not work/help at all.
Can also confirm it happens to a wide variety of blocks from different mods. Even Trees from Tech Reborn that grew with bonemeal aren't showing up properly.

I'm not sure if it's an issue with the Fabric API because I couldn't find a single issue ticket on their end (Github/Discord) concerning this bug.

**Comment by recon88** [comment] 2022-02-07 11:59
After further investigation, I think this is a multiplayer only issue. 
Wasn't able to reproduce it in a singleplayer world.
I even downloaded the world we are using on our server and the issue is gone when I import it into singleplayer.

**Comment by kiartu** [comment] 2022-02-08 17:16
> After further investigation, I think this is a multiplayer only issue. Wasn't able to reproduce it in a singleplayer world. I even downloaded the world we are using on our server and the issue is gone when I import it into singleplayer.
> 
> If it helps anything, here are two GIFs:
> 
> 1. TechReborn machines vanishing after Block Update triggered by activating the machines
> 2. Rubber Tree by TechReborn not showing after using bonemeal on it's sapling to grow it
>    https://imgur.com/a/WvBZv0o
> 
> As said, this happens to various mods, not just TechReborn. Used that as an example as it is easy to reproduce.
> 
> Edit: Installed a new instance with just fabric/api and tech reborn, no issues at all. I guess it must be an issue with either a mod conflicting with the rendering and/or block updates, or a sync issue.

recon88, please let us know if you figure out a temp solution. My server's been all but abandoned until it's fixed. =)

**Comment by itsdinkd** [comment] 2022-02-08 17:43
> After further investigation, I think this is a multiplayer only issue. Wasn't able to reproduce it in a singleplayer world. I even downloaded the world we are using on our server and the issue is gone when I import it into singleplayer.
> 
> If it helps anything, here are two GIFs:
> 
>     1. TechReborn machines vanishing after Block Update triggered by activating the machines
> 
>     2. Rubber Tree by TechReborn not showing after using bonemeal on it's sapling to grow it
>        https://imgur.com/a/WvBZv0o
> 
> 
> As said, this happens to various mods, not just TechReborn. Used that as an example as it is easy to reproduce.
> 
> Edit: Installed a new instance with just fabric/api and tech reborn, no issues at all. I guess it must be an issue with either a mod conflicting with the rendering and/or block updates, or a sync issue.

Thank you for this. Looks like it's due to a updated mod conflicting with rendering. There were no new mods added for 2.0.2. Problem is, there was 70+ mod updates. Sodium extra was updated, worth checking into.

**Comment by busterbrown1999** [comment] 2022-02-20 03:07
Fixed in 2.0.3

**Closed by busterbrown1999** 2022-02-20 03:07 UTC
Labels: bug
