### ISSUE TITLE
[BUG] Potion of healing produces "Server Closed" message, and unexpected exception in log

### ISSUE THREAD

**Issue by tslindsay** [itsdinkd/AQM2#84] opened 2022-01-22 21:41 UTC
**Modpack Version**
What modpack version
_1.4.1_

**Minecraft Version**
What mc version
_1.18.1_

**Describe the crash or bug**
_Drinking a potion of healing immediately kicks the player to the menu, throwing them a "Server closed" message. Log produces a "Encountered an unexpected exception" error._ 

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
_Drink a potion of healing._

**Expected behavior**
What is the expected outcome?
_Be healed._

**Screenshots**
Post screenshots if available
![image](https://user-images.githubusercontent.com/52063389/150656345-1a3784e9-f90b-408f-ac1d-601904f438d1.png)

**Crash log or latest.log.log**
https://pastebin.com/d0M77baz

**Additional context**
Any additional context?
_Received the potion from a witch. Playing on singleplayer local world; NOT playing on multiplayer server._

**Comment by Archiplex** [comment] 2022-01-23 02:16
I wasn't sure if it was directly related to my own issue, since this is on singleplayer and not multiplayer, but probably related? https://github.com/itsdinkd/AQM2/issues/86

**Comment by tslindsay** [comment] 2022-01-23 02:37
I’m sure the issues are related- some issue with health potions causes the server to crash, even if it’s an internal, single-player server.

**Comment by Archiplex** [comment] 2022-01-23 04:24
The multiplayer server doesn't actually crash, it just gives an odd error and kicks the drinker out, hence why I wasn't certain if it was the same. But it's *probably* linked

**Comment by tslindsay** [comment] 2022-01-23 04:49
Oh that’s interesting, that makes it seem like it’s a client side problem then.

**Comment by Archiplex** [comment] 2022-01-23 10:14
Something to add to this: If you have the "Surprise Gift" enchant while drinking instant health potions (on a server), it will boot you out and create 2 potions where you disconnected, without consuming the IH potions. Basically infinite potions

**Comment by MapleNe** [comment] 2022-01-25 05:51
i have this problem  too pls fix it 


[13:41:45] [Server thread/INFO] (class_2983) [STDOUT]: Negative index in crash report handler (0/11)
[13:41:45] [Server thread/WARN] (class_3242) Failed to handle packet for /223.73.26.80:8085
 net.minecraft.class_148: Ticking player
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:543) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:213) ~[?:?]
        at net.minecraft.network.ClientConnection.tick(ClientConnection:238) ~[?:?]
        at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:890) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:324) ~[?:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhp000$modifiedRunLoop(MinecraftServer:5356) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException

**Comment by itsdinkd** [comment] 2022-01-26 21:47
Duplicate of #86

**Closed by itsdinkd** 2022-01-26 21:47 UTC
Labels: bug
