### ISSUE TITLE
[BUG]Botania Weapon Issues

### ISSUE THREAD

**Issue by bobman9** [itsdinkd/AQM2#223] opened 2023-04-26 07:52 UTC
**Modpack Version**

1.5.1

**Minecraft Version**

1.19.4

**Describe the crash or bug**

The weapons, terra blade, starcaller, and thunderblade from the botania mod are not using the combat mod (forgot the name of it) and are using vanilla combat with no auto swing.  

Also, the starcaller projectile is invisible (not sure if modpack issue or botania itself).

**Steps to reproduce the behavior:**

Swing weapons, test starcaller for projectile visibility

**Expected behavior**

Expected outcome was the autoswing mechanic

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Not much else to say, the weapons kind of suck compared to lesser ones due to how much better the enhanced combat is with the modpack, yet are far more time consuming to get

**Comment by itsdinkd** [comment] 2023-04-29 23:13
Duplicate of #170 and #153

**Closed as completed by itsdinkd** 2023-04-29 23:13 UTC
Labels: bug
