### ISSUE TITLE
items not in tomb after death.

### ISSUE THREAD

**Issue by christomite** [itsdinkd/AQM2#33] opened 2022-06-04 14:23 UTC
**Modpack Version**
1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
items not dropping from tomb after death

**Steps to reproduce the behavior:**
not sure sometimes it works sometimes it dont.

**Expected behavior**
items return after right-clicking tomb.

**Comment by itsdinkd** [comment] 2022-06-07 22:29
Duplicate of #25

**Closed as completed by itsdinkd** 2022-06-07 22:29 UTC
Labels: bug
