### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Roakai** [itsdinkd/AQM2#138] opened 2022-02-17 23:05 UTC
**AQM2-2.0.4.1**
What modpack version

**1.18.2**
What mc version

**Game crashed when i equipped a terrasteal chest plate with phantom ink in my armor slot then put a promethium chest plate in my vanity armor slot and it crashed my game. now every time i open my inventory it crashes my game. **

**equip a terrasteal chest plate with phantom ink in your armor slot and a promethium chest plate in your vanity armor slot:**
How can someone replicate this bug/crash?

**Game with shut down and you will end up on desktop**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**i am in the End**
Any additional context?
[2022-02-17-3.log.gz](https://github.com/itsdinkd/AQM2/files/8092799/2022-02-17-3.log.gz)
[2022-02-17-2.log.gz](https://github.com/itsdinkd/AQM2/files/8092800/2022-02-17-2.log.gz)

**Comment by itsdinkd** [comment] 2022-02-25 18:54
If by vanity you mean cosmetic slot, this is a duplicate of #122 

Also please follow the template, upload your logs to pastebin.com and provide the link. and also please title your issue next time. Thanks

**Closed by itsdinkd** 2022-02-25 18:54 UTC
Labels: bug
