### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SilverEagle123** [itsdinkd/AQM2#41] opened 2022-01-09 11:04 UTC
**Modpack Version**
1.5.2
**Minecraft Version**
1.8.1
**Describe the bug**

In the mod: applied energistics2 you can craft fluix crystals mady out of fuix dust by throwing a combination of items in a water pool. if you look up for the recipe for fluix dust there is an entry (when you hover your mouse over it) which says: throwing in water. if you click it the game will close without error message.

**To Reproduce**
1. Go to your inventory
2. search for fluix dust
3. leftclick on fluix dust
3. hover mouse over the tabs to find throwing in water.
4. click it
5. See error

**Expected behavior**
A clear and concise description for the item combination for this recipe

**Comment by itsdinkd** [comment] 2022-01-09 19:24
Duplicate of https://github.com/itsdinkd/AQM2/issues/22

**Closed by itsdinkd** 2022-01-09 19:24 UTC
Labels: bug
