### ISSUE TITLE
[BUG] MC Dungeon armors crash in cosmetic slots.

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#122] opened 2022-02-07 20:11 UTC
**Modpack Version**
2,0,2,a

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Hungry Horror armor crashes game when put into cosmetic slots.

**Steps to reproduce the behavior:**
place hungry horror armor into cosmetic slots.

**Expected behavior**
fancy costmetics

**Crash log or latest.log.log**
https://pastebin.com/0176NGEk

**Comment by vydax** [comment] 2022-02-07 20:16
oh i just found out its not the only armor that crashes you, gourdian also did it. i assume that more armors from mc dungeons will crash you in a similair way.

**Comment by chronosacaria** [comment] 2022-02-09 23:54
I have been unable to reproduce this crash with the latest version of each mod involved (MCDA, Cloth Config, Cosmetic Armour and Trinkets). It would appear that there might be something else that is causing the issue. Did the server crash or just the client?

**Comment by vydax** [comment] 2022-02-10 04:12
Its when im playing on a server, anyone that is near me will crash too but not the server so i guess client side.

If it is any different i wear metallurgium armor highly enchanted and it first happened when i tried the helmet on the rest of my cosmetic slots had the dark lord armor from mcdoom. and i have various trinkets.

**Comment by itsdinkd** [comment] 2022-02-10 07:18
I couldn't replicate this either. I think this person did some crazy shit
to make it crash. I've tried numerous MCDA armors. Worked as intended in
cosmetic slot.

**Comment by itsdinkd** [comment] 2022-02-10 07:19
> Its when im playing on a server, anyone that is near me will crash too but not the server so i guess client side.
> 
> If it is any different i wear metallurgium armor highly enchanted and it first happened when i tried the helmet on the rest of my cosmetic slots had the dark lord armor from mcdoom. and i have various trinkets.

Did you try to reproduce in single player? I couldn't reproduce in SP, I didn't think about trying it in a server though.

**Comment by vydax** [comment] 2022-02-10 07:23
I have not tried it in single player, i wil try later today when im back home, ill update you here.

**Comment by itsdinkd** [comment] 2022-04-30 01:39
fixed in 2.1.4

**Closed by itsdinkd** 2022-04-30 01:39 UTC
Labels: bug
