### ISSUE TITLE
[BUG] Drinking potions crashes client

### ISSUE THREAD

**Issue by KalloJin** [itsdinkd/AQM2#52] opened 2022-01-11 02:17 UTC
**Modpack Version** 1.6

**Minecraft Version** 1.18.1

**Describe the bug**
Currently when ever a client drinks a potion it will crash them to the main menu and when they return the potion will still be unused and within their inventory

**To Reproduce**
1. Drink potion

**Expected behavior**
To be able to drink the potion

**Additional context**
Have tried on single player maps and on a server with the same result.

**Comment by Sebas-Re** [comment] 2022-01-11 06:56
Can confirm it happens when drinking any (or atleast most) vanilla potions, and only the drinkable types, not the lingering or the splash ones.
Error shown when you get kicket out ofthe game:
![image](https://user-images.githubusercontent.com/32151264/148894769-198d7d13-f081-4aea-b830-5174228cda8c.png)

latest.log: https://paste.corebot.dev/xisiyutusi.md

**Comment by Lucciolina** [comment] 2022-01-12 02:43
I also experienced this bug in both smp and singleplayer and after researching a bit, this seems to be caused by the rpgstats mod conflicting with mc dungeons armors.  The rpgstats mod author just released a hotfix a few hours ago that seems to have solved the problem.  I'm able to drink both vanilla potions and brews from bewitchment normally again.  Hopefully the rpgstats hotfix can be added to AQM2 in the future :)

**Comment by Sebas-Re** [comment] 2022-01-12 02:48
dungeon 

> I also experienced this bug in both smp and singleplayer and after researching a bit, this seems to be caused by the rpgstats mod conflicting with mc dungeons armors. The rpgstats mod author just released a hotfix a few hours ago that seems to have solved the problem. I'm able to drink both vanilla potions and brews from bewitchment normally again. Hopefully the rpgstats hotfix can be added to AQM2 in the future :)

That's great! Thanks for letting us know!

**Comment by itsdinkd** [comment] 2022-01-13 18:11
Fixed with latest RPGStats

**Closed by itsdinkd** 2022-01-13 18:11 UTC
Labels: bug
