### ISSUE TITLE
[BUG] Terralith not pulling seed from Server.Properties (server)

### ISSUE THREAD

**Issue by GooseCarnival** [itsdinkd/AQM2#93] opened 2022-08-29 17:07 UTC
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
From fresh serverpack install running via Windows Powershell, server generates from the same seed. Identical terrain, however random structure generation, modded and vanilla. 

**Steps to reproduce the behavior:**
Before server start, delete "world" folder in server files, and run "start.ps1" with any seed defined in "server.properties."

**Expected behavior**
New generation from different seeds. 

**Additional Info**
The generated terrain is spawn on the river shore, ocean to the north, and across river to the west is split between a forest and a cherry blossom forest. 
![2022-08-29_10 05 20](https://user-images.githubusercontent.com/95973911/187255599-8ee99b5a-6249-4c54-86a8-0c6290d99d71.png)

**Comment by miftner** [comment] 2022-09-11 14:38
I stumbled about this bug too.
The Problem is that Terralith doesnt use the seed provided in the server.properites. Instead it uses the seed defined in MINECRAFTFOLDER/kubejs/data/minecraft/overworld.json. Although there is a toggle to use the server.properties-Seed instead of this one, this toggle seems to only work with Forge and doesn't with fabric

Just change the seed in overworld.json and be happy :-)

**Comment by itsdinkd** [comment] 2023-01-15 00:51
Closing as 1.18.2 is sunset

-

Also this is fixed in 1.19.2 aqm2 you can enter seeds as normal now

**Closed as completed by itsdinkd** 2023-01-15 00:51 UTC
Labels: bug
