### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SilverEagle123** [itsdinkd/AQM2#57] opened 2022-01-11 20:50 UTC
**Modpack Version**
1.6
**Minecraft Version**
1.18.1
**Describe the bug**
Coal Ore can't be macerated to coal crushed dust anymore

**To Reproduce**
1. Set up a Macerator 
2. put coal ore in it 
3. compare with lignite coal ore (which works)

**Comment by Antoninecek** [comment] 2022-01-12 09:04
Duplicate of https://github.com/itsdinkd/AQM2/issues/53

**Closed** 2022-01-13 18:13 UTC
Labels: bug
