### ISSUE TITLE
[BUG] Portal to mining dimension (PureMiningDimension) not working 

### ISSUE THREAD

**Issue by cryptonis13** [itsdinkd/AQM2#104] opened 2022-09-12 21:19 UTC
**Modpack Version**
1.6

**Minecraft Version**
1.18.2

**Describe the crash or bug**
When attempting to teleport to the mining dimension (from the mod PureMiningDimension) via the portal, nothing happens. The visual distortion effect still appears and the typical portal sound plays.

**Steps to reproduce the behavior:**
Build a portal out of Mining Dimension Portal Blocks (4x5 frame) and light it by right-clicking with a Diamond Pickaxe. Then walk into it.

**Expected behavior**
The player walking into the portal is teleported to the mining dimension.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5845011/189758237-cd4b56e9-7104-4d41-ae90-e4feb8d78c8d.png)

**Crash log or latest.log.log**
No crash or event in the log.

**Additional context**
I tried teleporting to the dimension with `/dimteleport pureminingdimension:mining_dimension 0 0 0`, but the dimension does not seem to be recognized. Only the dimensions from ae2, agape, compactmachines, dimdoors and minecraft appear in the autocomplete window. I do have a folder `world/dimensions/pureminingdimension/mining_dimension`, though.

**Comment by itsdinkd** [comment] 2022-09-13 19:23
Logs please; both server and client

**Comment by cryptonis13** [comment] 2022-09-14 08:35
Here are the server and client logs:
- [server_log_part1](https://pastebin.com/haXue1w2), [server_log_part2](https://pastebin.com/i9AcNTDZ)
- [client_log](https://pastebin.com/77y9jyW2)

Interestingly, the portal only fails to work on the server. I created a new singeplayer world to test and it works fine in it.

**Comment by Knoxxar** [comment] 2022-09-16 09:44
We have the same problem on our server. Dimdoors have the same problem, here is a snippet from my log:

`[12:04:19] [Server thread/ERROR]: Teleporting failed with the following exception: 
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_14178()" because the return value of "org.dimdev.dimdoors.pockets.PocketGenerationContext.world()" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:140) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:194) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:81) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:77) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.DimensionalPortalBlock.onEntityCollision(DimensionalPortalBlock.java:66) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock:927) ~[?:?]
        at net.minecraft.entity.Entity.checkBlockCollision(Entity:1028) ~[?:?]
        at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity:768) ~[?:?]
        at net.minecraft.entity.Entity.move(Entity:737) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler:903) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:114) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$PositionAndOnGround.apply(PlayerMoveC2SPacket:42) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cgi000$modifiedRunLoop(MinecraftServer:6405) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:858) [?:?]`

**Comment by Seceroth** [comment] 2022-09-18 00:30
Same problem here. Something in the update has removed it from the level.dat even. I updated from 1.5 to 1.6.
This is 1.6:
![LevelDat1 6](https://user-images.githubusercontent.com/20866237/190880350-60cd0c6a-5011-469f-ba29-c79daf7a523f.PNG)
And this is 1.5:
![LevelDat1 5](https://user-images.githubusercontent.com/20866237/190880356-395db0f7-5307-453c-ab4b-9e4abf887092.PNG)
As you can see agape:europa_surface, agape:io, agape:titan, agape:venus_clouds, dimdoors:dungeon_pockets, dimdoors:personal_pockets, dimdoors:public_pockets, pureminingdimension:mining_dimension, spectrum:deeper_down_dimension and voidz:void are all gone. The dimensions are not registered anymore.
Trying the Voidz portal tells you "Failed to find void world, was it registered?" and Dimdoors gives the error above.

**Comment by EvanTheProgrammer** [comment] 2022-09-21 23:37
I am the dev of Pure Mining Dimension and this issue is caused by the latest terrablender update and should be fixed in the new modpack version 1.6.1 that is coming soon.

See screenshot for confirmation by dinked
![Screenshot 2022-09-21 193143](https://user-images.githubusercontent.com/86786575/191627840-a6a0a263-b3cb-430d-b8d2-40a2a07298b8.png)

**Closed as completed** 2022-11-17 00:02 UTC
Labels: bug
