### ISSUE TITLE
[BUG] Modern Industrialization Salt Not implemented correctly. 

### ISSUE THREAD

**Issue by Dres-Tiefling** [itsdinkd/AQM2#70] opened 2022-07-08 01:56 UTC
**Modpack Version**
What modpack version 1.3.3 AQM2 Fabric

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Salt ore generated by quarry is not implemented correctly. When macerated into Salt Dust you can not do anything with it.  You can not use polymorph in any crafting table to turn it into another salt product like bewitchment salt (most ideal solution likely). High levels of salt are needed for MI. This needs to be corrected.

**Steps to reproduce the behavior:**
Use electric quarry, get salt ore, try do anything with it.

**Expected behavior**
Salt dust could be used in MI recipes.  Possibly it also have use with polymorph mod.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Update: Croptopia Salt also not used in any recipe. Seems this is a polymorph issue.

**Comment by Dres-Tiefling** [comment] 2022-07-09 01:46
updated to include croptopia salt issue, and remove REI issue. I missed it.

**Comment by itsdinkd** [comment] 2022-07-09 05:15
Duplicate of #61 

Salt is unified.  You can easily convert croptopia salt into bewitchment salt (which is the main salt) by throwing it on the ground or by putting it in the crafting table, i forget ehich method isntrue for salt. Same goes for any other salt with the exception of MI Salt

**Closed as completed by itsdinkd** 2022-07-09 05:15 UTC
Labels: bug

**Comment by Dres-Tiefling** [comment] 2022-07-09 10:32
> Duplicate of #61
> 
> Salt is unified. You can easily convert croptopia salt into bewitchment salt (which is the main salt) by throwing it on the ground or by putting it in the crafting table, i forget ehich method isntrue for salt. Same goes for any other salt with the exception of MI Salt

Cant figure out how to convert croptopia salt. Not working ion crafting tables (tried many types) or "throwing it on ground" which just makes no sense anyway.

**Comment by itsdinkd** [comment] 2022-07-09 16:49
> > Duplicate of #61
> > Salt is unified. You can easily convert croptopia salt into bewitchment salt (which is the main salt) by throwing it on the ground or by putting it in the crafting table, i forget ehich method isntrue for salt. Same goes for any other salt with the exception of MI Salt
> 
> Cant figure out how to convert croptopia salt. Not working ion crafting tables (tried many types) or "throwing it on ground" which just makes no sense anyway.

There is a unification script to convert certain unified items into the chosen item when thrown on the ground. i didnt add it for salt it seems, only certain food items, so scratch that method.

How are you getting Croptopia Salt and MI salt anyways? the ore has been disabled along time ago.

![image](https://user-images.githubusercontent.com/35115304/178115273-f512d269-9f47-409d-a416-72dcda66ad37.png)

**Comment by Laff70** [comment] 2022-07-09 17:05
While we're talking about it, Sandwichable salt is also not unified with all other salt.

**Comment by Dres-Tiefling** [comment] 2022-07-09 19:43
> > > Duplicate of #61
> > > Salt is unified. You can easily convert croptopia salt into bewitchment salt (which is the main salt) by throwing it on the ground or by putting it in the crafting table, i forget ehich method isntrue for salt. Same goes for any other salt with the exception of MI Salt
> > 
> > 
> > Cant figure out how to convert croptopia salt. Not working ion crafting tables (tried many types) or "throwing it on ground" which just makes no sense anyway.
> 
> There is a unification script to convert certain unified items into the chosen item when thrown on the ground. i didnt add it for salt it seems, only certain food items, so scratch that method.
> 
> How are you getting Croptopia Salt and MI salt anyways? the ore has been disabled along time ago.
> 
> ![image](https://user-images.githubusercontent.com/35115304/178115273-f512d269-9f47-409d-a416-72dcda66ad37.png)

MI salt is from the electric quarry form MI, croptopia salt is from putting croptopia water bottles into a furnace.

**Comment by Dres-Tiefling** [comment] 2022-07-09 19:44
> While we're talking about it, Sandwichable salt is also not unified with all other salt.

Yah its always been its own thing for pickles, though a slimming down to one salt would be cool. I have a feeling there is an issue why it wasnt done.

**Comment by itsdinkd** [comment] 2022-07-09 21:22
This is because it has its own unique use for the mod. It will not be
unified
