### ISSUE TITLE
[BUG] Unable to complete Grow Crystals quest Certus crystal seeds and fluix crystal seeds removed 

### ISSUE THREAD

**Issue by Wolfen198** [itsdinkd/AQM2#145] opened 2023-01-20 22:57 UTC
**Modpack Version**
1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Required items for progression of FTBquests not present in modpack
![image](https://user-images.githubusercontent.com/122255553/213819566-98d55a54-dc60-468d-8f63-ce695b162373.png)
![image](https://user-images.githubusercontent.com/122255553/213819579-34848f32-b311-4203-b605-dad8b967f24e.png)
![image](https://user-images.githubusercontent.com/122255553/213819729-35d71f15-2255-49c7-b30b-44e7bdff4bd8.png)

**Steps to reproduce the behavior**
How can someone replicate this bug/crash?

**Expected behavior**
Requirements for Grow Crystal quest being only Certus Quartz Crystal and Fluix Crystal.  Quest text changed accordingly.

**Crash log or latest.log.log**
N/A

**Additional context**
Any additional context?

**Comment by xErrorAmelie** [comment] 2023-01-21 09:38
I can confirm that seeds are no longer existant.

**Comment by itsdinkd** [comment] 2023-01-21 10:21
Duplicate of #135

**Closed as completed by itsdinkd** 2023-01-21 10:21 UTC
Labels: bug
